stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/net
        - cp -frv ./include/net $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libnet.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libnet.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_net $UT_PATH

    only:
        - master

asp:
    stage: trigger
    script:
        - curl -X POST -F token=6e12a151c6bc41923513bf91baca20 -F ref=master $GITLAB_URL/api/v4/projects/13/trigger/pipeline
    only:
        - master
